/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 2.0.1.281.2
    Soft IP Version: 1.0.1
    Sun Jun 14 13:44:45 2020
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module PLL_DEV_16M (ref_clk_i, rst_n_i, bypass_i, lock_o, outcore_o,
    outglobal_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ref_clk_i;
    input  rst_n_i;
    input  bypass_i;
    output  lock_o;
    output  outcore_o;
    output  outglobal_o;
endmodule